### ISSUE TITLE
[VSCode] Python Multiline string Highlighting different than PyCharm

### ISSUE THREAD

**Issue by ShubhamBelwal** [gaplo917/GapStyle#12]
I just tried out GapStyle in VSCode and noticed that multi line string is colored in green (like docstring) while it is yellow in PyCharm (like regular string)

[Screenshot for the issue](https://1drv.ms/u/s!AiadJi2PXcrBsAdOkIIpIRYxMboQ?e=NVJjWh)

**Comment by gaplo917** [comment]
Thank you for reporting the issue. 

1. Multi-line string issue. This is definitely a bug!

2. `inp`, because python plugin not support semantic highlighting. 

GapStyle VS is purely depends on the language plugins that how richness is the implementation of syntax highlight & semantic highlight (most of the plugins does not as rich as IntelliJ). At this moment, will try to make a work around to get the syntax highlighting correct. 

Really appreciate your bug reporting💪🏻

**Comment by ShubhamBelwal** [comment]
>`inp`, because python plugin not support semantic highlighting.
> 
> GapStyle VS is purely depends on the language plugins that how richness is the implementation of syntax highlight & semantic highlight (most of the plugins does not as rich as IntelliJ). At this moment, will try to make a work around to get the syntax highlighting correct.

That makes sense. Thanks for the amazing extension and for bringing this to vscode. 😃
