### ISSUE TITLE
2018.2.4 issues

### ISSUE THREAD

**Issue by gaplo917** [gaplo917/GapStyle#4]
* [x] Python keyword color switch to green
* [x] .jade  file not render properly
* [x] Java & Kotlin keyword color is damaged by color inheritence
* [x] Kotlin Smart cast styling enhancement
* [x] HTML color inheritence issue & double check other language

**Comment by Aerogirl10** [comment]
Hey, are you planning to add more Sublime color to html and css in your scheme? Pink for tag names, green for classes etc?

**Comment by gaplo917** [comment]
@Aerogirl10 Current style should be look like this.

![image](https://user-images.githubusercontent.com/5468398/46742809-5cffb980-ccda-11e8-9fad-f50262240fe7.png)

You can see the syntax highlight options provided by intellij do not include "classes". So there is no way to add.

**Comment by Aerogirl10** [comment]
Wooo, In my panel it looks like this. I thought that I did something but Restore Defaults is inactive so it couldn't be me.
![phpstorm](https://user-images.githubusercontent.com/40596877/46743546-9c61e200-cca9-11e8-9a8b-466432ff9efd.PNG)

**Comment by gaplo917** [comment]
@Aerogirl10 Thanks for reporting. Very likely is color inheritance issue.

Current work around should be all settings in HTML, manually tick the right-bottom "inherit values from:" checkbox

![image](https://user-images.githubusercontent.com/5468398/46743918-a4874500-ccdc-11e8-8d76-a66a4afaf512.png)


Will fix it on next release

**Comment by Aerogirl10** [comment]
Sweet, thanks!
Btw, after uninstalling it and adding manually 

> Preference -> Editor -> Color Scheme -> click the settings icon(next to the scheme name) -> import scheme -> select GapStyle.jar
there is the same issue (but always worth to try other way around ;)) 

Just one thing, even if I check everywhere "inherit values from", one tag - HTML code - foreground is still wrong (#A9B7C6 instead of #F8F8F2). That is just a little thing that I can change in General - Default text, but maybe you will want to polish it up as well.

Great plug, love it! Keep up the great work. Customer service answering in minutes is just a dream 😄
